### ISSUE TITLE
Message Object should be one shared object for sender and receiver

### ISSUE THREAD

**Issue by snaco** [Turnt-SNACO/temc#1]
Since the message object will always contain the same fields there is no reason to have the class in both packages.

**Comment by RobertKats** [comment]
Unless we have to add more information for user, This way we can add more info in the future.

**Comment by snaco** [comment]
Then we would definitely want it to be one object instead of two so we only have to update one instead of both.  The message object should not change its data fields regardless of whether it's being sent or received.
